{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart.fullname" . }}-metrics-monitor
  {{- with (default dict .Values.commonAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
  labels:
    component: metrics
    {{- include "labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: {{ ternary "https" "http" .Values.metrics.secure }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      {{- if .Values.metrics.secure }}
      tlsConfig:
        insecureSkipVerify: true
      {{- end }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
{{- end }}
