apiVersion: as-code.io/v1
kind: ClusterEchelon
metadata:
  name: platform-wave-0
  labels:
    app.kubernetes.io/name: echelon-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  members:
    flux-kustomizations:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      namespaces:
        - flux-system
      selector:
        matchLabels:
          wave: "0"
      emptySetPolicy: NotReady
    platform-helmreleases:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      namespaceSelector:
        matchLabels:
          tier: platform
      selector:
        matchLabels:
          wave: "0"
      emptySetPolicy: Unknown
