apiVersion: as-code.io/v1
kind: Echelon
metadata:
  name: wave-0
  namespace: flux-system
  labels:
    app.kubernetes.io/name: echelon-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  members:
    kustomizations:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      selector:
        matchLabels:
          wave: "0"
      emptySetPolicy: NotReady
    helmreleases:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      selector:
        matchLabels:
          wave: "0"
      emptySetPolicy: Unknown
