apiVersion: as-code.io/v1
kind: Echelon
metadata:
  labels:
    app.kubernetes.io/name: echelon-operator
    app.kubernetes.io/managed-by: kustomize
  name: echelon-sample
spec:
  # TODO(user): Add fields here
